DROP TABLE IF EXISTS t_file;


CREATE TABLE t_file
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  create_name VARCHAR(30) NULL DEFAULT NULL COMMENT '创建人姓名',
  from_ip VARCHAR(100) NULL DEFAULT NULL COMMENT '创建人ip',
  file_name VARCHAR(100) NULL DEFAULT NULL COMMENT '文件名',
  file_path VARCHAR(100) NULL DEFAULT NULL COMMENT '文件路径',
  create_time VARCHAR(30) NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (id)
);


DROP TABLE IF EXISTS t_edit;


CREATE TABLE t_edit
(
    id BIGINT(20) NOT NULL COMMENT '主键ID',
    content CLOB NULL DEFAULT NULL COMMENT '内容',
    update_time TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
);
